// Dados reais importados da planilha "Gustavo Camargo — controle escritório 2026".
// Recebimentos (Pix) de janeiro a junho de 2026, extraídos dos extratos do BB.
// Gerado a partir do arquivo original; nomes truncados pelo extrato foram preservados
// para revisão. Total de receitas: R$ 94.029,88 em 145 lançamentos / 67 clientes.

import type { Cliente, Lancamento } from "./types";

export const CLIENTES_2026: Partial<Cliente>[] = [
  { id: "imp26c-larissamedeir", tipo: "pf", nome: "Larissa Medeir", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-josepedroiva", tipo: "pf", nome: "JOSE PEDRO IVA", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-anacarolined", tipo: "pf", nome: "ANA CAROLINE D", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-andreafarias", tipo: "pf", nome: "Andrea Farias", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-fernandagomes", tipo: "pf", nome: "Fernanda Gomes", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-cesarmorei", tipo: "pf", nome: "CESAR MOREI", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-vanessaapa", tipo: "pf", nome: "VANESSA APA", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-anaclarabarb", tipo: "pf", nome: "ANA CLARA BARB", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-joycefernanda", tipo: "pf", nome: "Joyce Fernanda", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-mateusadriano", tipo: "pf", nome: "Mateus Adriano", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-renatafernand", tipo: "pf", nome: "RENATA FERNAND", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-joaoluizdeo", tipo: "pf", nome: "JOAO LUIZ DE O", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-sandraregina", tipo: "pf", nome: "Sandra Regina", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-mariafernanda", tipo: "pf", nome: "Maria Fernanda", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-daianedasilv", tipo: "pf", nome: "Daiane da Silv", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-andersoncampo", tipo: "pf", nome: "Anderson Campo", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-valquiriapach", tipo: "pf", nome: "VALQUIRIA PACH", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-marlimoraesc", tipo: "pf", nome: "Marli Moraes C", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-mariadefatim", tipo: "pf", nome: "MARIA DE FATIM", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-paulacristina", tipo: "pf", nome: "PAULA CRISTINA", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-rayssadomingu", tipo: "pf", nome: "Rayssa Domingu", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-robisomcharle", tipo: "pf", nome: "ROBISOM CHARLE", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-camilabraz", tipo: "pf", nome: "CAMILA BRAZ", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-madlenearibe", tipo: "pf", nome: "MADLENE A RIBE", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-daianesaar", tipo: "pf", nome: "DAIANE SAAR", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-alessandraas", tipo: "pf", nome: "ALESSANDRA A S", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-karinapres", tipo: "pf", nome: "KARINA PRES", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-rosemaryalc", tipo: "pf", nome: "ROSEMARY A L C", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-julianaant", tipo: "pf", nome: "JULIANA ANT", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-wagnerdeo", tipo: "pf", nome: "WAGNER DE O", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-roselinarodri", tipo: "pf", nome: "Roselina Rodri", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-casodebora", tipo: "pf", nome: "Caso Debora", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-karinadomi", tipo: "pf", nome: "KARINA DOMI", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-pietroalvesz", tipo: "pf", nome: "Pietro Alves Z", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-veruskaamaro", tipo: "pf", nome: "VERUSKA AMARO", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-keilasteph", tipo: "pf", nome: "KEILA STEPH", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-rivaneidebarb", tipo: "pf", nome: "RIVANEIDE BARB", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-cristianef", tipo: "pf", nome: "CRISTIANE F", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-larissafernan", tipo: "pf", nome: "Larissa Fernan", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-wesleydemede", tipo: "pf", nome: "WESLEY DE MEDE", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-maikjulio", tipo: "pf", nome: "MAIK JULIO", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-luanfrancisco", tipo: "pf", nome: "Luan Francisco", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-mirivitoria", tipo: "pf", nome: "Miriã Vitoria", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-danielarodrig", tipo: "pf", nome: "Daniela Rodrig", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-gilmaramac", tipo: "pf", nome: "GILMARA MAC", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-danielebarbos", tipo: "pf", nome: "Daniele Barbos", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-nataliajan", tipo: "pf", nome: "NATALIA JAN", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-rodrigofer", tipo: "pf", nome: "RODRIGO FER", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-iracemafeliza", tipo: "pf", nome: "IRACEMA FELIZA", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-tatianeeri", tipo: "pf", nome: "TATIANE ERI", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-gustavorob", tipo: "pf", nome: "GUSTAVO ROB", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-analauralope", tipo: "pf", nome: "Ana Laura Lope", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-viniciusfu", tipo: "pf", nome: "VINICIUS FU", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-edvanlemes", tipo: "pf", nome: "Edvan Lemes", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-rayssavitoria", tipo: "pf", nome: "RAYSSA VITORIA", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-camilabarbosa", tipo: "pf", nome: "CAMILA BARBOSA", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-vanessademel", tipo: "pf", nome: "Vanessa de Mel", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-anapaulapere", tipo: "pf", nome: "ANA PAULA PERE", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-brunodeol", tipo: "pf", nome: "BRUNO DE OL", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-analaurar", tipo: "pf", nome: "ANA LAURA R", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-valdeciant", tipo: "pf", nome: "VALDECI ANT", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-luanadonizeti", tipo: "pf", nome: "Luana Donizeti", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-evertonferrei", tipo: "pf", nome: "EVERTON FERREI", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-vanderleia", tipo: "pf", nome: "VANDERLEIA", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-hoteltalu", tipo: "pf", nome: "HOTEL TALU", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
  { id: "imp26c-romerrodrigue", tipo: "pf", nome: "Romer Rodrigue", notas: "Importado da planilha de controle 2026." },
  { id: "imp26c-secrdare", tipo: "pf", nome: "SECR. DA RE", notas: "Importado da planilha de controle 2026. Nome possivelmente truncado pelo extrato bancário — revisar/completar." },
];

export const LANCAMENTOS_2026: Partial<Lancamento>[] = [
  { id: "imp26l-001", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-larissamedeir", descricao: "Honorários — Larissa Medeir", valor: 375.0, vencimento: "2026-01-02", pago_em: "2026-01-02", forma_pagamento: "PIX" },
  { id: "imp26l-002", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-josepedroiva", descricao: "Honorários — JOSE PEDRO IVA", valor: 300.0, vencimento: "2026-01-05", pago_em: "2026-01-05", forma_pagamento: "PIX" },
  { id: "imp26l-003", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-anacarolined", descricao: "Honorários — ANA CAROLINE D", valor: 300.0, vencimento: "2026-01-06", pago_em: "2026-01-06", forma_pagamento: "PIX" },
  { id: "imp26l-004", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-andreafarias", descricao: "Honorários — Andrea Farias", valor: 1000.0, vencimento: "2026-01-07", pago_em: "2026-01-07", forma_pagamento: "PIX" },
  { id: "imp26l-005", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-fernandagomes", descricao: "Honorários — Fernanda Gomes", valor: 500.0, vencimento: "2026-01-07", pago_em: "2026-01-07", forma_pagamento: "PIX" },
  { id: "imp26l-006", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-cesarmorei", descricao: "Honorários — CESAR MOREI", valor: 400.0, vencimento: "2026-01-07", pago_em: "2026-01-07", forma_pagamento: "PIX" },
  { id: "imp26l-007", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-anacarolined", descricao: "Honorários — ANA CAROLINE D", valor: 125.0, vencimento: "2026-01-08", pago_em: "2026-01-08", forma_pagamento: "PIX" },
  { id: "imp26l-008", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-anacarolined", descricao: "Honorários — ANA CAROLINE D", valor: 75.0, vencimento: "2026-01-09", pago_em: "2026-01-09", forma_pagamento: "PIX" },
  { id: "imp26l-009", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-vanessaapa", descricao: "Honorários — VANESSA APA", valor: 50.0, vencimento: "2026-01-09", pago_em: "2026-01-09", forma_pagamento: "PIX" },
  { id: "imp26l-010", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-anaclarabarb", descricao: "Honorários — ANA CLARA BARB", valor: 750.0, vencimento: "2026-01-12", pago_em: "2026-01-12", forma_pagamento: "PIX" },
  { id: "imp26l-011", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-joycefernanda", descricao: "Honorários — Joyce Fernanda", valor: 300.0, vencimento: "2026-01-12", pago_em: "2026-01-12", forma_pagamento: "PIX" },
  { id: "imp26l-012", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-mateusadriano", descricao: "Honorários — Mateus Adriano", valor: 200.0, vencimento: "2026-01-14", pago_em: "2026-01-14", forma_pagamento: "PIX" },
  { id: "imp26l-013", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-renatafernand", descricao: "Honorários — RENATA FERNAND", valor: 450.0, vencimento: "2026-01-16", pago_em: "2026-01-16", forma_pagamento: "PIX" },
  { id: "imp26l-014", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-joaoluizdeo", descricao: "Honorários — JOAO LUIZ DE O", valor: 22.5, vencimento: "2026-01-16", pago_em: "2026-01-16", forma_pagamento: "PIX" },
  { id: "imp26l-015", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-sandraregina", descricao: "Honorários — Sandra Regina", valor: 400.0, vencimento: "2026-01-19", pago_em: "2026-01-19", forma_pagamento: "PIX" },
  { id: "imp26l-016", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-mariafernanda", descricao: "Honorários — Maria Fernanda", valor: 300.0, vencimento: "2026-01-19", pago_em: "2026-01-19", forma_pagamento: "PIX" },
  { id: "imp26l-017", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-daianedasilv", descricao: "Honorários — Daiane da Silv", valor: 450.0, vencimento: "2026-01-20", pago_em: "2026-01-20", forma_pagamento: "PIX" },
  { id: "imp26l-018", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-andersoncampo", descricao: "Honorários — Anderson Campo", valor: 400.0, vencimento: "2026-01-20", pago_em: "2026-01-20", forma_pagamento: "PIX" },
  { id: "imp26l-019", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-valquiriapach", descricao: "Honorários — VALQUIRIA PACH", valor: 600.0, vencimento: "2026-01-20", pago_em: "2026-01-20", forma_pagamento: "PIX" },
  { id: "imp26l-020", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-marlimoraesc", descricao: "Honorários — Marli Moraes C", valor: 450.0, vencimento: "2026-01-20", pago_em: "2026-01-20", forma_pagamento: "PIX" },
  { id: "imp26l-021", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-mariadefatim", descricao: "Honorários — MARIA DE FATIM", valor: 350.0, vencimento: "2026-01-21", pago_em: "2026-01-21", forma_pagamento: "PIX" },
  { id: "imp26l-022", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-paulacristina", descricao: "Honorários — PAULA CRISTINA", valor: 500.0, vencimento: "2026-01-23", pago_em: "2026-01-23", forma_pagamento: "PIX" },
  { id: "imp26l-023", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-anacarolined", descricao: "Honorários — ANA CAROLINE D", valor: 300.0, vencimento: "2026-01-26", pago_em: "2026-01-26", forma_pagamento: "PIX" },
  { id: "imp26l-024", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-larissamedeir", descricao: "Honorários — Larissa Medeir", valor: 375.0, vencimento: "2026-01-27", pago_em: "2026-01-27", forma_pagamento: "PIX" },
  { id: "imp26l-025", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-joaoluizdeo", descricao: "Honorários — JOAO LUIZ DE O", valor: 65.0, vencimento: "2026-01-30", pago_em: "2026-01-30", forma_pagamento: "PIX" },
  { id: "imp26l-026", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-rayssadomingu", descricao: "Honorários — Rayssa Domingu", valor: 150.0, vencimento: "2026-02-02", pago_em: "2026-02-02", forma_pagamento: "PIX" },
  { id: "imp26l-027", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-robisomcharle", descricao: "Honorários — ROBISOM CHARLE", valor: 300.0, vencimento: "2026-02-02", pago_em: "2026-02-02", forma_pagamento: "PIX" },
  { id: "imp26l-028", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-josepedroiva", descricao: "Honorários — JOSE PEDRO IVA", valor: 300.0, vencimento: "2026-02-03", pago_em: "2026-02-03", forma_pagamento: "PIX" },
  { id: "imp26l-029", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-camilabraz", descricao: "Honorários — CAMILA BRAZ", valor: 500.0, vencimento: "2026-02-04", pago_em: "2026-02-04", forma_pagamento: "PIX" },
  { id: "imp26l-030", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-madlenearibe", descricao: "Honorários — MADLENE A RIBE", valor: 250.0, vencimento: "2026-02-05", pago_em: "2026-02-05", forma_pagamento: "PIX" },
  { id: "imp26l-031", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-mateusadriano", descricao: "Honorários — Mateus Adriano", valor: 200.0, vencimento: "2026-02-06", pago_em: "2026-02-06", forma_pagamento: "PIX" },
  { id: "imp26l-032", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-marlimoraesc", descricao: "Honorários — Marli Moraes C", valor: 450.0, vencimento: "2026-02-06", pago_em: "2026-02-06", forma_pagamento: "PIX" },
  { id: "imp26l-033", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-daianesaar", descricao: "Honorários — DAIANE SAAR", valor: 300.0, vencimento: "2026-02-06", pago_em: "2026-02-06", forma_pagamento: "PIX" },
  { id: "imp26l-034", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-alessandraas", descricao: "Honorários — ALESSANDRA A S", valor: 300.0, vencimento: "2026-02-06", pago_em: "2026-02-06", forma_pagamento: "PIX" },
  { id: "imp26l-035", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-andreafarias", descricao: "Honorários — Andrea Farias", valor: 500.0, vencimento: "2026-02-06", pago_em: "2026-02-06", forma_pagamento: "PIX" },
  { id: "imp26l-036", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-karinapres", descricao: "Honorários — KARINA PRES", valor: 450.0, vencimento: "2026-02-09", pago_em: "2026-02-09", forma_pagamento: "PIX" },
  { id: "imp26l-037", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-rosemaryalc", descricao: "Honorários — ROSEMARY A L C", valor: 200.0, vencimento: "2026-02-09", pago_em: "2026-02-09", forma_pagamento: "PIX" },
  { id: "imp26l-038", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-julianaant", descricao: "Honorários — JULIANA ANT", valor: 400.0, vencimento: "2026-02-10", pago_em: "2026-02-10", forma_pagamento: "PIX" },
  { id: "imp26l-039", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-renatafernand", descricao: "Honorários — RENATA FERNAND", valor: 450.0, vencimento: "2026-02-18", pago_em: "2026-02-18", forma_pagamento: "PIX" },
  { id: "imp26l-040", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-sandraregina", descricao: "Honorários — Sandra Regina", valor: 400.0, vencimento: "2026-02-18", pago_em: "2026-02-18", forma_pagamento: "PIX" },
  { id: "imp26l-041", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-valquiriapach", descricao: "Honorários — VALQUIRIA PACH", valor: 600.0, vencimento: "2026-02-20", pago_em: "2026-02-20", forma_pagamento: "PIX" },
  { id: "imp26l-042", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-daianedasilv", descricao: "Honorários — Daiane da Silv", valor: 450.0, vencimento: "2026-02-20", pago_em: "2026-02-20", forma_pagamento: "PIX" },
  { id: "imp26l-043", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-andersoncampo", descricao: "Honorários — Anderson Campo", valor: 400.0, vencimento: "2026-02-20", pago_em: "2026-02-20", forma_pagamento: "PIX" },
  { id: "imp26l-044", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-wagnerdeo", descricao: "Honorários — WAGNER DE O", valor: 400.0, vencimento: "2026-02-20", pago_em: "2026-02-20", forma_pagamento: "PIX" },
  { id: "imp26l-045", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-paulacristina", descricao: "Honorários — PAULA CRISTINA", valor: 500.0, vencimento: "2026-02-23", pago_em: "2026-02-23", forma_pagamento: "PIX" },
  { id: "imp26l-046", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-anaclarabarb", descricao: "Honorários — ANA CLARA BARB", valor: 750.0, vencimento: "2026-02-23", pago_em: "2026-02-23", forma_pagamento: "PIX" },
  { id: "imp26l-047", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-roselinarodri", descricao: "Honorários — Roselina Rodri", valor: 400.0, vencimento: "2026-02-24", pago_em: "2026-02-24", forma_pagamento: "PIX" },
  { id: "imp26l-048", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-joaoluizdeo", descricao: "Honorários — JOAO LUIZ DE O", valor: 38.42, vencimento: "2026-02-25", pago_em: "2026-02-25", forma_pagamento: "PIX" },
  { id: "imp26l-049", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-casodebora", descricao: "Pago em dinheiro (não passou pelo extrato bancário) — lançado manualmente", valor: 30000.0, vencimento: "2026-02-28", pago_em: "2026-02-28", forma_pagamento: "PIX" },
  { id: "imp26l-050", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-karinadomi", descricao: "Honorários — KARINA DOMI", valor: 400.0, vencimento: "2026-03-02", pago_em: "2026-03-02", forma_pagamento: "PIX" },
  { id: "imp26l-051", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-mateusadriano", descricao: "Honorários — Mateus Adriano", valor: 400.0, vencimento: "2026-03-02", pago_em: "2026-03-02", forma_pagamento: "PIX" },
  { id: "imp26l-052", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-pietroalvesz", descricao: "Honorários — Pietro Alves Z", valor: 300.0, vencimento: "2026-03-02", pago_em: "2026-03-02", forma_pagamento: "PIX" },
  { id: "imp26l-053", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-anacarolined", descricao: "Honorários — ANA CAROLINE D", valor: 150.0, vencimento: "2026-03-03", pago_em: "2026-03-03", forma_pagamento: "PIX" },
  { id: "imp26l-054", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-josepedroiva", descricao: "Honorários — JOSE PEDRO IVA", valor: 300.0, vencimento: "2026-03-04", pago_em: "2026-03-04", forma_pagamento: "PIX" },
  { id: "imp26l-055", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-andreafarias", descricao: "Honorários — Andrea Farias", valor: 500.0, vencimento: "2026-03-05", pago_em: "2026-03-05", forma_pagamento: "PIX" },
  { id: "imp26l-056", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-robisomcharle", descricao: "Honorários — ROBISOM CHARLE", valor: 300.0, vencimento: "2026-03-05", pago_em: "2026-03-05", forma_pagamento: "PIX" },
  { id: "imp26l-057", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-mariadefatim", descricao: "Honorários — MARIA DE FATIM", valor: 350.0, vencimento: "2026-03-09", pago_em: "2026-03-09", forma_pagamento: "PIX" },
  { id: "imp26l-058", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-veruskaamaro", descricao: "Honorários — VERUSKA AMARO", valor: 100.0, vencimento: "2026-03-09", pago_em: "2026-03-09", forma_pagamento: "PIX" },
  { id: "imp26l-059", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-keilasteph", descricao: "Honorários — KEILA STEPH", valor: 300.0, vencimento: "2026-03-12", pago_em: "2026-03-12", forma_pagamento: "PIX" },
  { id: "imp26l-060", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-karinapres", descricao: "Honorários — KARINA PRES", valor: 450.0, vencimento: "2026-03-13", pago_em: "2026-03-13", forma_pagamento: "PIX" },
  { id: "imp26l-061", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-renatafernand", descricao: "Honorários — RENATA FERNAND", valor: 450.0, vencimento: "2026-03-13", pago_em: "2026-03-13", forma_pagamento: "PIX" },
  { id: "imp26l-062", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-sandraregina", descricao: "Honorários — Sandra Regina", valor: 400.0, vencimento: "2026-03-17", pago_em: "2026-03-17", forma_pagamento: "PIX" },
  { id: "imp26l-063", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-rivaneidebarb", descricao: "Honorários — RIVANEIDE BARB", valor: 200.0, vencimento: "2026-03-17", pago_em: "2026-03-17", forma_pagamento: "PIX" },
  { id: "imp26l-064", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-rivaneidebarb", descricao: "Honorários — RIVANEIDE BARB", valor: 100.0, vencimento: "2026-03-17", pago_em: "2026-03-17", forma_pagamento: "PIX" },
  { id: "imp26l-065", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-mateusadriano", descricao: "Honorários — Mateus Adriano", valor: 140.0, vencimento: "2026-03-18", pago_em: "2026-03-18", forma_pagamento: "PIX" },
  { id: "imp26l-066", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-cristianef", descricao: "Honorários — CRISTIANE F", valor: 400.0, vencimento: "2026-03-19", pago_em: "2026-03-19", forma_pagamento: "PIX" },
  { id: "imp26l-067", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-valquiriapach", descricao: "Honorários — VALQUIRIA PACH", valor: 600.0, vencimento: "2026-03-20", pago_em: "2026-03-20", forma_pagamento: "PIX" },
  { id: "imp26l-068", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-larissafernan", descricao: "Honorários — Larissa Fernan", valor: 300.0, vencimento: "2026-03-20", pago_em: "2026-03-20", forma_pagamento: "PIX" },
  { id: "imp26l-069", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-andersoncampo", descricao: "Honorários — Anderson Campo", valor: 400.0, vencimento: "2026-03-20", pago_em: "2026-03-20", forma_pagamento: "PIX" },
  { id: "imp26l-070", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-daianedasilv", descricao: "Honorários — Daiane da Silv", valor: 450.0, vencimento: "2026-03-23", pago_em: "2026-03-23", forma_pagamento: "PIX" },
  { id: "imp26l-071", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-paulacristina", descricao: "Honorários — PAULA CRISTINA", valor: 500.0, vencimento: "2026-03-25", pago_em: "2026-03-25", forma_pagamento: "PIX" },
  { id: "imp26l-072", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-wesleydemede", descricao: "Honorários — WESLEY DE MEDE", valor: 1500.0, vencimento: "2026-03-26", pago_em: "2026-03-26", forma_pagamento: "PIX" },
  { id: "imp26l-073", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-maikjulio", descricao: "Honorários — MAIK JULIO", valor: 300.0, vencimento: "2026-03-27", pago_em: "2026-03-27", forma_pagamento: "PIX" },
  { id: "imp26l-074", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-luanfrancisco", descricao: "Honorários — Luan Francisco", valor: 80.0, vencimento: "2026-03-30", pago_em: "2026-03-30", forma_pagamento: "PIX" },
  { id: "imp26l-075", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-anacarolined", descricao: "Honorários — ANA CAROLINE D", valor: 225.0, vencimento: "2026-04-01", pago_em: "2026-04-01", forma_pagamento: "PIX" },
  { id: "imp26l-076", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-josepedroiva", descricao: "Honorários — JOSE PEDRO IVA", valor: 300.0, vencimento: "2026-04-06", pago_em: "2026-04-06", forma_pagamento: "PIX" },
  { id: "imp26l-077", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-andreafarias", descricao: "Honorários — Andrea Farias", valor: 450.0, vencimento: "2026-04-07", pago_em: "2026-04-07", forma_pagamento: "PIX" },
  { id: "imp26l-078", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-mirivitoria", descricao: "Honorários — Miriã Vitoria", valor: 600.0, vencimento: "2026-04-14", pago_em: "2026-04-14", forma_pagamento: "PIX" },
  { id: "imp26l-079", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-renatafernand", descricao: "Honorários — RENATA FERNAND", valor: 450.0, vencimento: "2026-04-15", pago_em: "2026-04-15", forma_pagamento: "PIX" },
  { id: "imp26l-080", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-danielarodrig", descricao: "Honorários — Daniela Rodrig", valor: 230.0, vencimento: "2026-04-16", pago_em: "2026-04-16", forma_pagamento: "PIX" },
  { id: "imp26l-081", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-cesarmorei", descricao: "Honorários — CESAR MOREI", valor: 200.0, vencimento: "2026-04-17", pago_em: "2026-04-17", forma_pagamento: "PIX" },
  { id: "imp26l-082", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-sandraregina", descricao: "Honorários — Sandra Regina", valor: 400.0, vencimento: "2026-04-17", pago_em: "2026-04-17", forma_pagamento: "PIX" },
  { id: "imp26l-083", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-karinapres", descricao: "Honorários — KARINA PRES", valor: 450.0, vencimento: "2026-04-20", pago_em: "2026-04-20", forma_pagamento: "PIX" },
  { id: "imp26l-084", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-andersoncampo", descricao: "Honorários — Anderson Campo", valor: 400.0, vencimento: "2026-04-20", pago_em: "2026-04-20", forma_pagamento: "PIX" },
  { id: "imp26l-085", tipo: "receita", categoria: "Honorários", descricao: "Confirmar de qual cliente/caso é esse depósito", valor: 5000.0, vencimento: "2026-04-22", pago_em: "2026-04-22", forma_pagamento: "Espécie" },
  { id: "imp26l-086", tipo: "receita", categoria: "Honorários", descricao: "Confirmar de qual cliente/caso é esse depósito", valor: 200.0, vencimento: "2026-04-22", pago_em: "2026-04-22", forma_pagamento: "Espécie" },
  { id: "imp26l-087", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-daianedasilv", descricao: "Honorários — Daiane da Silv", valor: 450.0, vencimento: "2026-04-22", pago_em: "2026-04-22", forma_pagamento: "PIX" },
  { id: "imp26l-088", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-valquiriapach", descricao: "Honorários — VALQUIRIA PACH", valor: 600.0, vencimento: "2026-04-22", pago_em: "2026-04-22", forma_pagamento: "PIX" },
  { id: "imp26l-089", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-marlimoraesc", descricao: "Honorários — Marli Moraes C", valor: 480.0, vencimento: "2026-04-22", pago_em: "2026-04-22", forma_pagamento: "PIX" },
  { id: "imp26l-090", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-paulacristina", descricao: "Honorários — PAULA CRISTINA", valor: 500.0, vencimento: "2026-04-22", pago_em: "2026-04-22", forma_pagamento: "PIX" },
  { id: "imp26l-091", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-gilmaramac", descricao: "Honorários — GILMARA MAC", valor: 300.0, vencimento: "2026-04-23", pago_em: "2026-04-23", forma_pagamento: "PIX" },
  { id: "imp26l-092", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-mateusadriano", descricao: "Honorários — Mateus Adriano", valor: 300.0, vencimento: "2026-04-23", pago_em: "2026-04-23", forma_pagamento: "PIX" },
  { id: "imp26l-093", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-danielarodrig", descricao: "Honorários — Daniela Rodrig", valor: 230.0, vencimento: "2026-04-23", pago_em: "2026-04-23", forma_pagamento: "PIX" },
  { id: "imp26l-094", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-danielebarbos", descricao: "Honorários — Daniele Barbos", valor: 1500.0, vencimento: "2026-04-23", pago_em: "2026-04-23", forma_pagamento: "PIX" },
  { id: "imp26l-095", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-nataliajan", descricao: "Honorários — NATALIA JAN", valor: 300.0, vencimento: "2026-04-24", pago_em: "2026-04-24", forma_pagamento: "PIX" },
  { id: "imp26l-096", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-anacarolined", descricao: "Honorários — ANA CAROLINE D", valor: 300.0, vencimento: "2026-04-27", pago_em: "2026-04-27", forma_pagamento: "PIX" },
  { id: "imp26l-097", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-anaclarabarb", descricao: "Honorários — ANA CLARA BARB", valor: 750.0, vencimento: "2026-05-04", pago_em: "2026-05-04", forma_pagamento: "PIX" },
  { id: "imp26l-098", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-anacarolined", descricao: "Honorários — ANA CAROLINE D", valor: 225.0, vencimento: "2026-05-04", pago_em: "2026-05-04", forma_pagamento: "PIX" },
  { id: "imp26l-099", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-mateusadriano", descricao: "Honorários — Mateus Adriano", valor: 200.0, vencimento: "2026-05-05", pago_em: "2026-05-05", forma_pagamento: "PIX" },
  { id: "imp26l-100", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-rodrigofer", descricao: "Honorários — RODRIGO FER", valor: 200.0, vencimento: "2026-05-06", pago_em: "2026-05-06", forma_pagamento: "PIX" },
  { id: "imp26l-101", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-iracemafeliza", descricao: "Honorários — IRACEMA FELIZA", valor: 300.0, vencimento: "2026-05-07", pago_em: "2026-05-07", forma_pagamento: "PIX" },
  { id: "imp26l-102", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-luanfrancisco", descricao: "Honorários — Luan Francisco", valor: 22.0, vencimento: "2026-05-07", pago_em: "2026-05-07", forma_pagamento: "PIX" },
  { id: "imp26l-103", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-tatianeeri", descricao: "Honorários — TATIANE ERI", valor: 350.0, vencimento: "2026-05-08", pago_em: "2026-05-08", forma_pagamento: "PIX" },
  { id: "imp26l-104", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-rodrigofer", descricao: "Honorários — RODRIGO FER", valor: 800.0, vencimento: "2026-05-08", pago_em: "2026-05-08", forma_pagamento: "PIX" },
  { id: "imp26l-105", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-andreafarias", descricao: "Honorários — Andrea Farias", valor: 500.0, vencimento: "2026-05-08", pago_em: "2026-05-08", forma_pagamento: "PIX" },
  { id: "imp26l-106", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-gustavorob", descricao: "Nome truncado no extrato — confirmar remetente", valor: 1903.16, vencimento: "2026-05-08", pago_em: "2026-05-08", forma_pagamento: "PIX" },
  { id: "imp26l-107", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-analauralope", descricao: "Honorários — Ana Laura Lope", valor: 400.0, vencimento: "2026-05-13", pago_em: "2026-05-13", forma_pagamento: "PIX" },
  { id: "imp26l-108", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-sandraregina", descricao: "Honorários — Sandra Regina", valor: 400.0, vencimento: "2026-05-15", pago_em: "2026-05-15", forma_pagamento: "PIX" },
  { id: "imp26l-109", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-karinapres", descricao: "Honorários — KARINA PRES", valor: 300.0, vencimento: "2026-05-18", pago_em: "2026-05-18", forma_pagamento: "PIX" },
  { id: "imp26l-110", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-viniciusfu", descricao: "Honorários — VINICIUS FU", valor: 3695.67, vencimento: "2026-05-18", pago_em: "2026-05-18", forma_pagamento: "PIX" },
  { id: "imp26l-111", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-edvanlemes", descricao: "Honorários — Edvan Lemes", valor: 420.0, vencimento: "2026-05-20", pago_em: "2026-05-20", forma_pagamento: "PIX" },
  { id: "imp26l-112", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-andersoncampo", descricao: "Honorários — Anderson Campo", valor: 400.0, vencimento: "2026-05-20", pago_em: "2026-05-20", forma_pagamento: "PIX" },
  { id: "imp26l-113", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-valquiriapach", descricao: "Honorários — VALQUIRIA PACH", valor: 600.0, vencimento: "2026-05-22", pago_em: "2026-05-22", forma_pagamento: "PIX" },
  { id: "imp26l-114", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-karinapres", descricao: "Honorários — KARINA PRES", valor: 150.0, vencimento: "2026-05-22", pago_em: "2026-05-22", forma_pagamento: "PIX" },
  { id: "imp26l-115", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-paulacristina", descricao: "Honorários — PAULA CRISTINA", valor: 500.0, vencimento: "2026-05-22", pago_em: "2026-05-22", forma_pagamento: "PIX" },
  { id: "imp26l-116", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-joaoluizdeo", descricao: "Honorários — JOAO LUIZ DE O", valor: 12.25, vencimento: "2026-05-26", pago_em: "2026-05-26", forma_pagamento: "PIX" },
  { id: "imp26l-117", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-rodrigofer", descricao: "Honorários — RODRIGO FER", valor: 800.0, vencimento: "2026-05-29", pago_em: "2026-05-29", forma_pagamento: "PIX" },
  { id: "imp26l-118", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-rayssavitoria", descricao: "Honorários — RAYSSA VITORIA", valor: 200.0, vencimento: "2026-06-01", pago_em: "2026-06-01", forma_pagamento: "PIX" },
  { id: "imp26l-119", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-camilabarbosa", descricao: "Honorários — CAMILA BARBOSA", valor: 250.0, vencimento: "2026-06-02", pago_em: "2026-06-02", forma_pagamento: "PIX" },
  { id: "imp26l-120", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-anacarolined", descricao: "Honorários — ANA CAROLINE D", valor: 225.0, vencimento: "2026-06-03", pago_em: "2026-06-03", forma_pagamento: "PIX" },
  { id: "imp26l-121", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-vanessademel", descricao: "Honorários — Vanessa de Mel", valor: 500.0, vencimento: "2026-06-03", pago_em: "2026-06-03", forma_pagamento: "PIX" },
  { id: "imp26l-122", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-iracemafeliza", descricao: "Honorários — IRACEMA FELIZA", valor: 300.0, vencimento: "2026-06-05", pago_em: "2026-06-05", forma_pagamento: "PIX" },
  { id: "imp26l-123", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-anapaulapere", descricao: "Honorários — ANA PAULA PERE", valor: 800.0, vencimento: "2026-06-05", pago_em: "2026-06-05", forma_pagamento: "PIX" },
  { id: "imp26l-124", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-marlimoraesc", descricao: "Honorários — Marli Moraes C", valor: 330.0, vencimento: "2026-06-08", pago_em: "2026-06-08", forma_pagamento: "PIX" },
  { id: "imp26l-125", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-brunodeol", descricao: "Honorários — BRUNO DE OL", valor: 450.0, vencimento: "2026-06-08", pago_em: "2026-06-08", forma_pagamento: "PIX" },
  { id: "imp26l-126", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-andreafarias", descricao: "Honorários — Andrea Farias", valor: 500.0, vencimento: "2026-06-08", pago_em: "2026-06-08", forma_pagamento: "PIX" },
  { id: "imp26l-127", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-analaurar", descricao: "Honorários — ANA LAURA R", valor: 400.0, vencimento: "2026-06-09", pago_em: "2026-06-09", forma_pagamento: "PIX" },
  { id: "imp26l-128", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-valdeciant", descricao: "Honorários — VALDECI ANT", valor: 350.0, vencimento: "2026-06-10", pago_em: "2026-06-10", forma_pagamento: "PIX" },
  { id: "imp26l-129", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-karinapres", descricao: "Honorários — KARINA PRES", valor: 350.0, vencimento: "2026-06-15", pago_em: "2026-06-15", forma_pagamento: "PIX" },
  { id: "imp26l-130", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-luanadonizeti", descricao: "Honorários — Luana Donizeti", valor: 600.0, vencimento: "2026-06-15", pago_em: "2026-06-15", forma_pagamento: "PIX" },
  { id: "imp26l-131", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-evertonferrei", descricao: "Honorários — EVERTON FERREI", valor: 110.0, vencimento: "2026-06-15", pago_em: "2026-06-15", forma_pagamento: "PIX" },
  { id: "imp26l-132", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-vanderleia", descricao: "Honorários — VANDERLEIA", valor: 500.0, vencimento: "2026-06-17", pago_em: "2026-06-17", forma_pagamento: "PIX" },
  { id: "imp26l-133", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-sandraregina", descricao: "Honorários — Sandra Regina", valor: 400.0, vencimento: "2026-06-17", pago_em: "2026-06-17", forma_pagamento: "PIX" },
  { id: "imp26l-134", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-andersoncampo", descricao: "Honorários — Anderson Campo", valor: 400.0, vencimento: "2026-06-19", pago_em: "2026-06-19", forma_pagamento: "PIX" },
  { id: "imp26l-135", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-hoteltalu", descricao: "Honorários — HOTEL TALU", valor: 250.0, vencimento: "2026-06-19", pago_em: "2026-06-19", forma_pagamento: "PIX" },
  { id: "imp26l-136", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-edvanlemes", descricao: "Honorários — Edvan Lemes", valor: 420.0, vencimento: "2026-06-19", pago_em: "2026-06-19", forma_pagamento: "PIX" },
  { id: "imp26l-137", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-luanadonizeti", descricao: "Honorários — Luana Donizeti", valor: 300.0, vencimento: "2026-06-22", pago_em: "2026-06-22", forma_pagamento: "PIX" },
  { id: "imp26l-138", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-karinapres", descricao: "Honorários — KARINA PRES", valor: 100.0, vencimento: "2026-06-22", pago_em: "2026-06-22", forma_pagamento: "PIX" },
  { id: "imp26l-139", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-valquiriapach", descricao: "Honorários — VALQUIRIA PACH", valor: 600.0, vencimento: "2026-06-22", pago_em: "2026-06-22", forma_pagamento: "PIX" },
  { id: "imp26l-140", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-alessandraas", descricao: "Honorários — ALESSANDRA A S", valor: 300.0, vencimento: "2026-06-24", pago_em: "2026-06-24", forma_pagamento: "PIX" },
  { id: "imp26l-141", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-luanfrancisco", descricao: "Honorários — Luan Francisco", valor: 100.0, vencimento: "2026-06-24", pago_em: "2026-06-24", forma_pagamento: "PIX" },
  { id: "imp26l-142", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-wesleydemede", descricao: "Honorários — WESLEY DE MEDE", valor: 500.0, vencimento: "2026-06-26", pago_em: "2026-06-26", forma_pagamento: "PIX" },
  { id: "imp26l-143", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-romerrodrigue", descricao: "Honorários — Romer Rodrigue", valor: 400.0, vencimento: "2026-06-29", pago_em: "2026-06-29", forma_pagamento: "PIX" },
  { id: "imp26l-144", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-secrdare", descricao: "Honorários — SECR. DA RE", valor: 5.88, vencimento: "2026-06-30", pago_em: "2026-06-30", forma_pagamento: "PIX" },
  { id: "imp26l-145", tipo: "receita", categoria: "Honorários", cliente_id: "imp26c-paulacristina", descricao: "Honorários — PAULA CRISTINA", valor: 500.0, vencimento: "2026-06-30", pago_em: "2026-06-30", forma_pagamento: "PIX" },
];
